apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sql
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  00-schema.sql: |-
{{ .Files.Get "sql/00-schema.sql" | indent 4 }}
  10-seed.sql: |-
{{ .Files.Get "sql/10-seed.sql" | indent 4 }}
