namespace: iotag-sbx

postgres:
  host: iot-agent-postgres-postgresql.iotag-sbx.svc.cluster.local
  port: 5432
  database: iot_agent
  secretName: iot-agent-postgres-postgresql
  secretKey: password
  user: gte
  
auth:
  username: gte
  password: gte
  database: iot_agent
