namespace: iotag-dev

postgres:
  host: iot-agent-postgres-postgresql.iotag-dev.svc.cluster.local
  port: 5432
  database: iot_agent
  user: gte
  secretName: iot-agent-postgres-postgresql
  secretKey: password
